### PR TITLE
repository2: populate reverseLayers correctly

### LINKED ISSUE #184: failed to identify ports
```
$ docker2aci docker://prom/pushgateway
$ tar zxvf prom-pushgateway-latest.aci manifest
$ cat manifest 
```

returned 
```
{
   "acKind":"ImageManifest",
   "acVersion":"0.8.5",
   "name":"registry-1.docker.io/prom/pushgateway",
   "labels":[
      {
         "name":"version",
         "value":"latest"
      },
      {
         "name":"os",
         "value":"linux"
      },
      {
         "name":"arch",
         "value":"amd64"
      }
   ],
   "app":{
      "exec":[
         "sh"
      ],
      "user":"0",
      "group":"0"
   },
   "annotations":[
      {
         "name":"created",
         "value":"2016-03-18T18:22:48Z"
      },
      {
         "name":"appc.io/docker/registryurl",
         "value":"registry-1.docker.io"
      },
      {
         "name":"appc.io/docker/repository",
         "value":"prom/pushgateway"
      },
      {
         "name":"appc.io/docker/imageid",
         "value":"bc744c4ab376115cc45c610d53f529dd2d4249ae6b35e5d6e7a96e58863545aa"
      },
      {
         "name":"appc.io/docker/parentimageid",
         "value":"56ed16bd6310cca65920c653a9bb22de6b235990dcaa1742ff839867aed730e5"
      },
      {
         "name":"appc.io/docker/cmd",
         "value":"[\"sh\"]"
      },
      {
         "name":"appc.io/docker/tag",
         "value":"latest"
      }
   ]
}
```

notice that the PORTS is missing even though the current [Dockerfile](https://hub.docker.com/r/prom/pushgateway/~/dockerfile/) indicates that there is supposed to be port 9091 exposed.

### PR DESCRIPTION
**Pull request by iaguis**
In da56c93f we introduced an optimization to avoid going through all the
layers every time we need the index of a specific one.

However, when we set the layer index, we weren't setting the reversed
index, like we were doing before the optimization.

Fix it by setting the correct index.

Fixes #184

### CODE REVIEW

**Comment by jonboulle** [comment]
Test?

**Comment by iaguis** [comment]
Added a test.

**Comment by jonboulle** [comment]
@dgonyeo review?

**Comment by dgonyeo** [comment]
LGTM

**Pull request merged**
