### PR TITLE
lib/internal: allow auto fallback from v2 API to v1

### LINKED ISSUE #221: Need to support docker registries that store v1 and v2 images
Some registries appear to store images that are only accessible via the same registry api version that they were pushed through.

for example:
docker2aci docker://gcr.io/google_containers/kubedns-amd64:1.7 # works!
docker2aci docker://gcr.io/google_containers/skydns:2015-10-13-8c72f8c # 404

Because the code currently assumes that a registry only supports one api version and v2 is checked first, if the registry supports v2 then any v1 images are not accessible.

### PR DESCRIPTION
**Pull request by stuart-warren**
fixes #221
docker2aci would only attempt the v2 api if a registry supported it.
this check for a 404 error from the v2 api and if so attempts to
fallback to v1.

Workflow:
probe v2, try v2, downgrade-on-failure, probe v1, try v1,
hardfail-on-failure

### CODE REVIEW

**Comment by stuart-warren** [comment]
Hmm, I don't really understand the build failure here:
```
fatal: No names found, cannot describe anything.
```

**Comment by jonboulle** [comment]
That's some weird Semaphore flake where I think it doesn't check out the repository properly. I restarted it.

**Comment by jonboulle** [comment]
LGTM. @lucab ?

**Comment by lucab** [comment]
Code LGTM, but I'll give this a spin inside rkt testsuite just to make sure that we don't hit further regressions.

**Comment by lucab** [comment]
rkt testsuite is green too, merging. Thanks a lot @stuart-warren for your patches!

**Pull request merged**
