### PR TITLE
release 0.11.2

### PR DESCRIPTION
**Pull request by alban**
xref https://github.com/coreos/rkt/issues/2188#issuecomment-227550521

/cc @dgonyeo @s-urbaniak

### CODE REVIEW

**Comment by alban** [comment]
Do we want to get https://github.com/appc/docker2aci/pull/176 first?

**Comment by s-urbaniak** [comment]
I'd like #176 to land first, @dgonyeo thoughts?

**Comment by dgonyeo** [comment]
Sure, I'd be fine waiting for that.

**Comment by iaguis** [comment]
I think we should make this `0.12.0` because #176 is not just a bugfix.

**Comment by iaguis** [comment]
#179

**Pull request closed without merging**
