### PR TITLE
backend/repository: pull layers in parallel

### PR DESCRIPTION
**Pull request by iaguis**
This is #152 with a bugfix.

> To reduce the time it takes to fetch docker images, this commit modifies
the backends to pull each image layer concurrently. As a result,
github.com/coreos/pkg/progressutil is used in place of ioprogress to
draw the progress bars.

### CODE REVIEW

**Comment by jonboulle** [comment]
needs rebase?

**Comment by iaguis** [comment]
What?

**Comment by iaguis** [comment]
Hm, we can use the `coreos/pkg` tag directly, just asec.

**Comment by jonboulle** [comment]
outstanding
LGTMIIW

**Comment by iaguis** [comment]
LGTM

**Pull request merged**
