### PR TITLE
log: introduce Logger interface

### LINKED ISSUE #136: Allow custom logging in docker2aci lib.
Something to consider before releasing 1.0 in a separate PR - replace the `pkg/log` with a `Logger` field in the `CommonConfig` struct, so users can pass their own logger. The `Logger` fields would be of some interface type like:

``` go
type Logger interface {
    Debug(i ...interface{})
    Info(i ...interface{})
}
```

so the implementer could implement the `Debug` function in the same way as currently `pkg/log` does without resorting to some global boolean variable set by the `InitDebug()` function. Possibly export two implementation like `DefaultLogger` with configurable debugging function and `DevNullLogger`.

### PR DESCRIPTION
**Pull request by s-urbaniak**
This introduces a new Logger interface to allow swappable `debug`, and
`info` loggers for consumers of the library.

These loggers are compatible with the "log" stdlib logger.

This PR also does a refactoring/cleanup in preparation for #216.

Fixes #136

### CODE REVIEW

**Comment by s-urbaniak** [comment]
I did this in the plane, so let's see, if I pass the CI.

**Comment by euank** [comment]
LGTM, thanks for the refactoring!

**Comment by jonboulle** [comment]
Needs a rebase

**Comment by lucab** [comment]
Rebased, LGTM, merging. And thanks :)

**Pull request merged**
