### PR TITLE
Sanitize AC Names

### LINKED ISSUE #12: Error if the url contains custom port
```
$ ./docker2aci internal-registry.com:5000/demo:v0.5
Downloading layer: 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158
Conversion error: error building layer: error generating the manifest: invalid char in ACName: :
```

https://github.com/appc/docker2aci/blob/master/lib/docker2aci.go#L421
https://github.com/appc/docker2aci/blob/master/lib/docker2aci.go#L472

### PR DESCRIPTION
**Pull request by iaguis**
Make sure we pass valid strings to NewACName

Fixes #12

### CODE REVIEW

**Comment by jonboulle** [comment]
Actually, could you please just export this in the upstream repository?

**Comment by iaguis** [comment]
Should I also move sanitizeACName to upstream?

**Comment by jonboulle** [comment]
Sure, seems like a reasonable helper function. And a test table, please ;-)

**Comment by iaguis** [comment]
appc/spec#179

**Comment by iaguis** [comment]
Now that appc/spec#179 is merged we can merge this

**Pull request merged**
