### PR TITLE
lib/internal: fix tar header format

### PR DESCRIPTION
**Pull request by zhsj**
fix tar header format after manipulating the Name and Linkname.

Fixes: https://github.com/appc/docker2aci/issues/259

### CODE REVIEW

**Comment by zhsj** [comment]
The Format field is exposed since Go 1.10, should the CI bump its Go version?

**Comment by zhsj** [comment]
As long as it uses `archive/tar`, I don't find other way to workaround. But if you don't want to enforce docker2aci depending go1.10, I can change the PR to use build profile(like separating the fixture to a function, and only building that function on go1.10), but it looks ugly...

**Comment by lucab** [comment]
@iaguis any feedback? I would typically wait till 1.9 goes out of support (i.e. August 2018), but at the same time this seems worth fixing in a shorter term.

**Comment by zhsj** [comment]
Reading the reference issue on https://github.com/coreos/bugs/issues/2402, it seems docker2aci on CoreOS 1688.5.3 not affected by this. However I don't use CoreOS, not sure what version the docker2aci is uses. If this is a regression in docker2aci, then we can fix it without bumping Go dependency to 1.10.

**Comment by zhsj** [comment]
Reading the reference issue on https://github.com/coreos/bugs/issues/2402, it seems docker2aci on CoreOS 1688.5.3 not affected by this. However I don't use CoreOS, not sure what version the docker2aci is uses. If this is a regression in docker2aci, then we can fix it without bumping Go dependency to 1.10.

**Comment by zhsj** [comment]
As suggested in the issue of Go, I changed the PR to copy Header struct.

**Pull request merged**
