### PR TITLE
Statically link objects

### LINKED ISSUE #246: Clarify release target, provide statically linked ones
It is not clear from the releases page for what architecture the binary executables listed there are suitable.
Neither is it clear that they are dynamically linked. Because of the latter they do not work under Alpine Linux without jumping through hoops. Seems like this situation makes users miss out on a major use case for `docker2aci`, running inside Alpine Linux based build containers.

Can you clarify this and release statically linked, stripped executables?

### PR DESCRIPTION
**Pull request by sanmai-NL**
This makes docker2aci usable under non-glibc environments.
Resolves #246.

### CODE REVIEW

**Comment by sanmai-NL** [comment]
@lucab: Can you merge this, even considering the maintenance status, as you requested the PR in #246?

**Comment by sanmai-NL** [comment]
@lucab: since this project has been dormant for a few years, I'll close the PR. Can you mark it as archived on GitHub please?

**Comment by lucab** [comment]
Unfortunately I cannot directly, I'll try to find somebody with enough privileges to do so.
The umbrella project has been ended via https://github.com/rkt/rkt/issues/4024.

**Comment by sanmai-NL** [comment]
@lucab: you didn't get to it?

**Comment by lucab** [comment]
@philips @iaguis @vbatts we should go for a round of archivals here similar to https://github.com/rkt/rkt/pull/4026, but I don't have privileges on this organization to do so myself. Can any of you take care of this?

**Comment by philips** [comment]
you have owner role @lucab

**Comment by vbatts** [comment]
:+1:

**Pull request closed without merging**
